version: "3.8"

volumes: [db]

services:
  dbs:
  image: mcr.microsoft.com/mssql/server:2022-latest
  container_name: cobranca-db
  ports: [1433:1433]
  volumes: [db:/var/opt/mssql]
  environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=YourStrong!Passw0rd

  api:
    build: .
    depends_on: [dbs]
    container_name: cobranca-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=dbs;Database=CobrancaDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true
    ports: [5000:80]
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
